# -*- coding: utf-8 -*-
"""12062025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bQealDE8kO0mXk36l2FqQ6pefE66D95M
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import os

sale = pd.read_csv("retail_sales_dataset.csv")

print(sale.dtypes)
#view all data type for each coloum

print(sale.isnull().sum())
# to identify the null value in the each column

print(sale.duplicated().sum())
# find the duplicates if there is any

sale.head(5)
# print frist 5 row

sale.columns
# view the coloum in data set

sale['Date'].head(5)
#view top 5 row in a column

# Convert Date column to datetime format
sale['Date'] = pd.to_datetime(sale['Date'])

# Change format to DDMMYYYY
sale['Formatted_Date'] = sale['Date'].dt.strftime('%m-%d-%Y')

sale['Formatted_Date']
exact_date = sale.iloc[137]['Formatted_Date']
exact_date

sale.to_excel('cleaned_sales_data.xlsx', index=False)
# data visual using power BI

# forcasting the future sale for 2024 using ML model Prophet

import pandas as pd
from prophet import Prophet
import matplotlib.pyplot as plt
model = Prophet()
data = sale[['Formatted_Date', 'Total Amount']]
data.rename(columns={'Formatted_Date': 'ds', 'Total Amount': 'y'}, inplace=True)
model.fit(data)
future = model.make_future_dataframe(periods=12, freq='M')
forecast = model.predict(future)
model.plot(forecast)
plt.title("Sales Forecast for 2024")
plt.xlabel("Date")
plt.ylabel("Total Sales")
plt.show()



